from __future__ import annotations

from dataclasses import dataclass
from importlib import import_module
from typing import Callable


@dataclass(frozen=True)
class SurfaceOperation:
    resource: str
    operation: str
    module: str
    function: str
    kind: str = "wrapper"
    notes: str = ""


MCP_SOURCE_PARITY_SURFACE: tuple[SurfaceOperation, ...] = (
    SurfaceOperation("project", "get", "atomict.project.project", "get_project"),
    SurfaceOperation("project", "list", "atomict.project.project", "list_projects"),
    SurfaceOperation("project", "create", "atomict.project.project", "create_project"),
    SurfaceOperation("project", "update", "atomict.project.project", "update_project"),
    SurfaceOperation("project", "delete", "atomict.project.project", "delete_project"),
    SurfaceOperation("project", "exists", "atomict.project.project", "project_exists", kind="legacy"),
    SurfaceOperation("project", "get_by_name", "atomict.project.project", "get_project_by_name", kind="legacy"),
    SurfaceOperation("project-note", "get", "atomict.project.note", "get_project_note"),
    SurfaceOperation("project-note", "list", "atomict.project.note", "list_project_notes"),
    SurfaceOperation("project-note", "create", "atomict.project.note", "create_project_note"),
    SurfaceOperation("project-note", "update", "atomict.project.note", "update_project_note"),
    SurfaceOperation("project-note", "delete", "atomict.project.note", "delete_project_note"),
    SurfaceOperation("object-link", "get", "atomict.project.link", "get_object_link"),
    SurfaceOperation("object-link", "list", "atomict.project.link", "list_object_links"),
    SurfaceOperation("object-link", "create", "atomict.project.link", "create_object_link"),
    SurfaceOperation("object-link", "update", "atomict.project.link", "update_object_link"),
    SurfaceOperation("object-link", "delete", "atomict.project.link", "delete_object_link"),
    SurfaceOperation("project-workbench-layout", "get", "atomict.project.resources", "get_project_workbench_layout"),
    SurfaceOperation("project-workbench-layout", "list", "atomict.project.resources", "list_project_workbench_layouts"),
    SurfaceOperation("project-workbench-layout", "create", "atomict.project.resources", "create_project_workbench_layout"),
    SurfaceOperation("project-workbench-layout", "update", "atomict.project.resources", "update_project_workbench_layout"),
    SurfaceOperation("project-workbench-layout", "delete", "atomict.project.resources", "delete_project_workbench_layout"),
    SurfaceOperation("project-workbench", "get", "atomict.project.workbench", "get_workbench", kind="legacy"),
    SurfaceOperation("user", "get", "atomict.user.resources", "get_user"),
    SurfaceOperation("user", "list", "atomict.user.resources", "list_users"),
    SurfaceOperation("user", "update", "atomict.user.resources", "update_user"),
    SurfaceOperation("user", "delete", "atomict.user.resources", "delete_user"),
    SurfaceOperation("user-upload", "get", "atomict.user.files", "get_user_upload"),
    SurfaceOperation("user-upload", "list", "atomict.user.files", "list_user_uploads"),
    SurfaceOperation("user-upload", "upload", "atomict.user.files", "upload_single_file", kind="legacy"),
    SurfaceOperation("user-upload", "update", "atomict.user.files", "update_user_upload"),
    SurfaceOperation("user-upload", "delete", "atomict.user.files", "delete_user_upload"),
    SurfaceOperation("user-upload", "download", "atomict.user.files", "download_file", kind="legacy"),
    SurfaceOperation("user-upload", "download_content", "atomict.user.files", "download_user_upload_content"),
    SurfaceOperation("workspace", "lookup_simulation", "atomict.user.resources", "lookup_simulation_workspace"),
    SurfaceOperation("workspace", "clear", "atomict.user.workspace", "clear_workspace", kind="legacy"),
    SurfaceOperation("workspace", "download", "atomict.user.workspace", "download_workspace", kind="legacy"),
    SurfaceOperation("workspace", "upload", "atomict.user.workspace", "upload_workspace", kind="legacy"),
    SurfaceOperation("task", "get", "atomict.infra.distwork.task", "get_task"),
    SurfaceOperation("task", "list", "atomict.infra.distwork.task", "list_tasks"),
    SurfaceOperation("task", "cancel", "atomict.infra.distwork.task", "cancel_task"),
    SurfaceOperation("task", "update_status", "atomict.infra.distwork.task", "update_task_status", kind="legacy"),
    SurfaceOperation("task-status-history", "list", "atomict.infra.distwork.task", "get_task_status_history"),
    SurfaceOperation("organisation", "get", "atomict.organization_resources", "get_organisation"),
    SurfaceOperation("organisation", "list", "atomict.organization_resources", "list_organisations"),
    SurfaceOperation("organisation", "create", "atomict.organization_resources", "create_organisation"),
    SurfaceOperation("organisation", "update", "atomict.organization_resources", "update_organisation"),
    SurfaceOperation("organisation", "delete", "atomict.organization_resources", "delete_organisation"),
    SurfaceOperation("fhiaims-simulation", "get", "atomict.simulation.fhi_aims", "get_simulation"),
    SurfaceOperation("fhiaims-simulation", "list", "atomict.simulation.fhi_aims", "list_simulations"),
    SurfaceOperation("fhiaims-simulation", "create", "atomict.simulation.fhi_aims", "create_simulation"),
    SurfaceOperation("fhiaims-simulation", "update", "atomict.simulation.fhi_aims", "update_simulation"),
    SurfaceOperation("fhiaims-simulation", "delete", "atomict.simulation.fhi_aims", "delete_simulation"),
    SurfaceOperation("fhiaims-simulation-file", "get", "atomict.simulation.fhi_aims", "get_simulation_file"),
    SurfaceOperation("fhiaims-simulation-file", "list", "atomict.simulation.fhi_aims", "list_simulation_files"),
    SurfaceOperation("fhiaims-simulation-file", "create", "atomict.simulation.fhi_aims", "create_simulation_file"),
    SurfaceOperation("fhiaims-simulation-file", "update", "atomict.simulation.fhi_aims", "update_simulation_file"),
    SurfaceOperation("fhiaims-simulation-file", "delete", "atomict.simulation.fhi_aims", "delete_simulation_file"),
    SurfaceOperation("kpoint-exploration", "get", "atomict.simulation.kpoint", "get_kpoint_exploration"),
    SurfaceOperation("kpoint-exploration", "list", "atomict.simulation.kpoint", "list_kpoint_explorations"),
    SurfaceOperation("kpoint-exploration", "create", "atomict.simulation.kpoint", "create_kpoint_exploration"),
    SurfaceOperation("kpoint-exploration", "update", "atomict.simulation.kpoint", "update_kpoint_exploration"),
    SurfaceOperation("kpoint-exploration", "delete", "atomict.simulation.kpoint", "delete_kpoint_exploration"),
    SurfaceOperation("kpoint-simulation", "get", "atomict.simulation.kpoint", "get_kpoint_simulation"),
    SurfaceOperation("kpoint-simulation", "list", "atomict.simulation.kpoint", "list_kpoint_simulations"),
    SurfaceOperation("kpoint-simulation", "create", "atomict.simulation.kpoint", "create_kpoint_simulation"),
    SurfaceOperation("kpoint-simulation", "update", "atomict.simulation.kpoint", "update_kpoint_simulation"),
    SurfaceOperation("kpoint-simulation", "delete", "atomict.simulation.kpoint", "delete_kpoint_simulation"),
    SurfaceOperation("kpoint-analysis", "get", "atomict.simulation.kpoint", "get_kpoint_analysis"),
    SurfaceOperation("kpoint-analysis", "list", "atomict.simulation.kpoint", "list_kpoint_analyses"),
    SurfaceOperation("kpoint-analysis", "create", "atomict.simulation.kpoint", "create_kpoint_analysis"),
    SurfaceOperation("kpoint-analysis", "update", "atomict.simulation.kpoint", "update_kpoint_analysis"),
    SurfaceOperation("kpoint-analysis", "delete", "atomict.simulation.kpoint", "delete_kpoint_analysis"),
    SurfaceOperation("sqs-exploration", "get", "atomict.simulation.sqs", "get_sqs_exploration"),
    SurfaceOperation("sqs-exploration", "list", "atomict.simulation.sqs", "list_sqs_explorations"),
    SurfaceOperation("sqs-exploration", "create", "atomict.simulation.sqs", "create_sqs_exploration"),
    SurfaceOperation("sqs-exploration", "update", "atomict.simulation.sqs", "update_sqs_exploration"),
    SurfaceOperation("sqs-exploration", "delete", "atomict.simulation.sqs", "delete_sqs_exploration"),
    SurfaceOperation("sqs-simulation-file", "get", "atomict.simulation.sqs", "get_sqs_simulation_file"),
    SurfaceOperation("sqs-simulation-file", "list", "atomict.simulation.sqs", "list_sqs_simulation_files"),
    SurfaceOperation("sqs-simulation-file", "create", "atomict.simulation.sqs", "create_sqs_simulation_file"),
    SurfaceOperation("sqs-simulation-file", "update", "atomict.simulation.sqs", "update_sqs_simulation_file"),
    SurfaceOperation("sqs-simulation-file", "delete", "atomict.simulation.sqs", "delete_sqs_simulation_file"),
    SurfaceOperation("sqs-target-concentration", "get", "atomict.simulation.sqs", "get_sqs_target_concentration"),
    SurfaceOperation("sqs-target-concentration", "list", "atomict.simulation.sqs", "list_sqs_target_concentrations"),
    SurfaceOperation("sqs-target-concentration", "create", "atomict.simulation.sqs", "create_sqs_target_concentration"),
    SurfaceOperation("sqs-target-concentration", "update", "atomict.simulation.sqs", "update_sqs_target_concentration"),
    SurfaceOperation("sqs-target-concentration", "delete", "atomict.simulation.sqs", "delete_sqs_target_concentration"),
    SurfaceOperation("ea-exploration", "get", "atomict.simulation.ea", "get_ea_exploration"),
    SurfaceOperation("ea-exploration", "list", "atomict.simulation.ea", "list_ea_explorations"),
    SurfaceOperation("ea-exploration", "create", "atomict.simulation.ea", "create_ea_exploration"),
    SurfaceOperation("ea-exploration", "update", "atomict.simulation.ea", "update_ea_exploration"),
    SurfaceOperation("ea-exploration", "delete", "atomict.simulation.ea", "delete_ea_exploration"),
    SurfaceOperation("ea-exploration-sample", "get", "atomict.simulation.ea", "get_ea_exploration_sample"),
    SurfaceOperation("ea-exploration-sample", "list", "atomict.simulation.ea", "list_ea_exploration_samples"),
    SurfaceOperation("ea-exploration-sample", "create", "atomict.simulation.ea", "create_ea_exploration_sample"),
    SurfaceOperation("ea-exploration-sample", "update", "atomict.simulation.ea", "update_ea_exploration_sample"),
    SurfaceOperation("ea-exploration-sample", "delete", "atomict.simulation.ea", "delete_ea_exploration_sample"),
    SurfaceOperation("ea-exploration-analysis", "get", "atomict.simulation.ea", "get_ea_exploration_analysis"),
    SurfaceOperation("ea-exploration-analysis", "list", "atomict.simulation.ea", "list_ea_exploration_analyses"),
    SurfaceOperation("ea-exploration-analysis", "create", "atomict.simulation.ea", "create_ea_exploration_analysis"),
    SurfaceOperation("ea-exploration-analysis", "update", "atomict.simulation.ea", "update_ea_exploration_analysis"),
    SurfaceOperation("ea-exploration-analysis", "delete", "atomict.simulation.ea", "delete_ea_exploration_analysis"),
    SurfaceOperation("ea-exploration-analysis-file", "get", "atomict.simulation.ea", "get_ea_exploration_analysis_file"),
    SurfaceOperation("ea-exploration-analysis-file", "list", "atomict.simulation.ea", "list_ea_exploration_analysis_files"),
    SurfaceOperation("ea-exploration-analysis-file", "create", "atomict.simulation.ea", "create_ea_exploration_analysis_file"),
    SurfaceOperation("ea-exploration-analysis-file", "update", "atomict.simulation.ea", "update_ea_exploration_analysis_file"),
    SurfaceOperation("ea-exploration-analysis-file", "delete", "atomict.simulation.ea", "delete_ea_exploration_analysis_file"),
    SurfaceOperation("soec-exploration", "get", "atomict.simulation.ea", "get_soec_exploration", kind="alias"),
    SurfaceOperation("soec-exploration", "list", "atomict.simulation.ea", "list_soec_explorations", kind="alias"),
    SurfaceOperation("soec-exploration", "create", "atomict.simulation.ea", "create_soec_exploration", kind="alias"),
    SurfaceOperation("mlrelax", "get", "atomict.simulation.mlrelax", "get_mlrelaxation"),
    SurfaceOperation("mlrelax", "list", "atomict.simulation.mlrelax", "list_mlrelaxations"),
    SurfaceOperation("mlrelax", "create", "atomict.simulation.mlrelax", "create_mlrelaxation"),
    SurfaceOperation("mlrelax", "update", "atomict.simulation.mlrelax", "update_mlrelaxation"),
    SurfaceOperation("mlrelax", "delete", "atomict.simulation.mlrelax", "delete_mlrelaxation"),
    SurfaceOperation("mlrelax-file", "get", "atomict.simulation.mlrelax", "get_mlrelax_file"),
    SurfaceOperation("mlrelax-file", "list", "atomict.simulation.mlrelax", "list_mlrelax_files"),
    SurfaceOperation("mlrelax-file", "create", "atomict.simulation.mlrelax", "create_mlrelax_file"),
    SurfaceOperation("mlrelax-file", "update", "atomict.simulation.mlrelax", "update_mlrelax_file"),
    SurfaceOperation("mlrelax-file", "delete", "atomict.simulation.mlrelax", "delete_mlrelax_file"),
    SurfaceOperation("phonon-run", "get", "atomict.simulation.phonon", "get_phonon_run", kind="legacy"),
    SurfaceOperation("phonon-run", "create", "atomict.simulation.phonon", "create_phonon_run", kind="legacy"),
    SurfaceOperation("phonon-run-simulation", "get", "atomict.simulation.phonon", "get_phonon_sim_run", kind="legacy"),
    SurfaceOperation("phonon-run-simulation-file", "list", "atomict.simulation.phonon", "get_phonon_sim_run_files", kind="legacy"),
    SurfaceOperation("phonon-run-simulation-file", "associate_upload", "atomict.simulation.phonon", "associate_user_upload_with_phonon_sim_run", kind="legacy"),
    SurfaceOperation("md", "get", "atomict.simulation.md", "get_md_simulation", kind="legacy"),
    SurfaceOperation("md", "create", "atomict.simulation.md", "create_md_simulation", kind="legacy"),
    SurfaceOperation("md", "delete", "atomict.simulation.md", "delete_md_simulation", kind="legacy"),
    SurfaceOperation("md-file", "get", "atomict.simulation.md", "get_md_simulation_file", kind="legacy"),
    SurfaceOperation("md-file", "create", "atomict.simulation.md", "create_md_simulation_file", kind="legacy"),
    SurfaceOperation("md-file", "delete", "atomict.simulation.md", "delete_md_simulation_file", kind="legacy"),
    SurfaceOperation("md-file", "associate_upload", "atomict.simulation.md", "associate_user_upload_with_md_simulation", kind="legacy"),
    SurfaceOperation("defect-exploration", "get", "atomict.simulation.defect", "get_defect_exploration", kind="legacy"),
    SurfaceOperation("defect-exploration", "create", "atomict.simulation.defect", "create_defect_exploration", kind="legacy"),
    SurfaceOperation("defect-exploration-file", "get", "atomict.simulation.defect", "get_defect_exploration_file", kind="legacy"),
    SurfaceOperation("defect-exploration-file", "create", "atomict.simulation.defect", "create_defect_exploration_file", kind="legacy"),
    SurfaceOperation("defect-exploration-file", "associate_upload", "atomict.simulation.defect", "associate_user_upload_with_defect_exploration", kind="legacy"),
    SurfaceOperation("impact-simulation", "get", "atomict.simulation.impact", "get_impact_simulation", kind="legacy"),
    SurfaceOperation("impact-simulation-file", "list", "atomict.simulation.impact", "get_impact_simulation_files", kind="legacy"),
    SurfaceOperation("impact-simulation-file", "associate_upload", "atomict.simulation.impact", "associate_user_upload_with_impact_simulation", kind="legacy"),
    SurfaceOperation("encoding-task", "get", "atomict.simulation.sh", "get_sh", kind="legacy"),
    SurfaceOperation("encoding-file", "list", "atomict.simulation.sh", "get_sh_files", kind="legacy"),
    SurfaceOperation("encoding-file", "associate_upload", "atomict.simulation.sh", "associate_user_upload_with_sh", kind="legacy"),
)


def resolve_operation(operation: SurfaceOperation) -> Callable:
    module = import_module(operation.module)
    return getattr(module, operation.function)


def build_resource_registry() -> dict[str, dict[str, SurfaceOperation]]:
    registry: dict[str, dict[str, SurfaceOperation]] = {}
    for operation in MCP_SOURCE_PARITY_SURFACE:
        registry.setdefault(operation.resource, {})[operation.operation] = operation
    return registry


MCP_RESOURCE_REGISTRY = build_resource_registry()
